### ISSUE TITLE
Watchfaces stop syncing after several hours, being replaced by default one that can't be changed back

### ISSUE THREAD

**Issue by Odadjian** [bigdigital/watchdrip#18]
Hi,

I have encountered an issue - Watchdrip is working fine for couple of hours, then the watchface with glucose level disappears from the band, being replaced by default one - when trying to force the change by reenabling services in Watchdrip couple of times, I get error message on my band "can't sync" with red X. It seems that I need to reboot both the smartphone and band in order to restore the proper syncing. 

My phone: Xiaomi Redmi Note 8 Pro
My band: Mi Band 4

**Comment by kamfur00** [comment]
Hello, I have the same problem only MiBand6 and Samsung described in issue #8

**Comment by jo-wur** [comment]
Me too, I also have the same problem on MiBand6 and Samsung described in issue https://github.com/bigdigital/watchdrip/pull/8

**Comment by dircsem** [comment]
Here this seems to happen because the application is freezing.
It starts getting this OutOfMemoryError and also 
`java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 2403584 free bytes and 2347KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
                                                                                                    	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
                                                                                                    	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
                                                                                                    	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:300)
                                                                                                    	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 2403584 free bytes and 2347KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
                                                                                                    	at android.database.CursorWindow.nativeGetString(Native Method)
                                                                                                    	at android.database.CursorWindow.getString(CursorWindow.java:476)
                                                                                                    	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:54)
                                                                                                    	at com.reactiveandroid.internal.utils.SQLiteUtils.getColumnFieldValue(SQLiteUtils.java:223)
                                                                                                    	at com.reactiveandroid.internal.ModelAdapter.loadFromCursor(ModelAdapter.java:103)
                                                                                                    	at com.reactiveandroid.internal.utils.QueryUtils.processCursor(QueryUtils.java:81)
                                                                                                    	at com.reactiveandroid.internal.utils.QueryUtils.fetchModels(QueryUtils.java:45)
                                                                                                    	at com.reactiveandroid.query.ResultQueryBase.fetch(ResultQueryBase.java:26)
                                                                                                    	at com.thatguysservice.huami_xdrip.models.database.UserError.deletable(UserError.java:147)
                                                                                                    	at com.thatguysservice.huami_xdrip.models.database.UserError.cleanup(UserError.java:120)
                                                                                                    	at com.thatguysservice.huami_xdrip.utils.jobs.CleanupWorker.doWork(CleanupWorker.java:25)
                                                                                                    	at androidx.work.Worker$1.run(Worker.java:85)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012) `

When uploading the watch face to gts2mini
This error also happens, and this is the one tha freezes the app
` Process: com.thatguysservice.huami_xdrip, PID: 23613
                                                                                                    android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=com.thatguysservice.huami_xdrip/.services.BroadcastService (has extras) }: app is in background uid UidRecord{5900623 u0a382 TRNB idle change:procadj procs:0 seq(66012996,66012421)}
                                                                                                    	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1981)
                                                                                                    	at android.app.ContextImpl.startService(ContextImpl.java:1927)
                                                                                                    	at android.content.ContextWrapper.startService(ContextWrapper.java:834)
                                                                                                    	at com.thatguysservice.huami_xdrip.models.Helper.startService(Helper.java:89)
                                                                                                    	at com.thatguysservice.huami_xdrip.models.Helper.startService(Helper.java:75)
                                                                                                    	at com.thatguysservice.huami_xdrip.services.BroadcastService.bgForce(BroadcastService.java:87)
                                                                                                    	at com.thatguysservice.huami_xdrip.services.BroadcastService$1.run(BroadcastService.java:80)
                                                                                                    	at com.thatguysservice.huami_xdrip.UtilityModels.Inevitable$Task.poll(Inevitable.java:113)
                                                                                                    	at com.thatguysservice.huami_xdrip.UtilityModels.Inevitable.lambda$task$0(Inevitable.java:61)
                                                                                                    	at com.thatguysservice.huami_xdrip.UtilityModels.Inevitable$$ExternalSyntheticLambda0.run(Unknown Source:2)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)`
